# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: grafana-datasources
#   namespace: metrics
# data:
#   datasources.yaml: |
#     apiVersion: 1
#     datasources:
#       - name: MiAPI
#         type: simples-json-datasource
#         access: proxy
#         url: http://metrics-service.metrics.svc.cluster.local:8080/grafana
#         isDefault: true
# ---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: metrics
type: Opaque
stringData:
  admin-user: admin
  admin-password: admin123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-admin-credentials
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin-credentials
                  key: admin-password
      #     volumeMounts:
      #       - name: ds-config
      #         mountPath: /etc/grafana/provisioning/datasources
      # volumes:
      #   - name: ds-config
      #     configMap:
      #       name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: metrics
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
